"""
Django settings for appsplatform project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os, sys
from os.path import  basename, dirname, join

from decouple import Config, RepositoryEnv



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = dirname(dirname(dirname(os.path.abspath(__file__))))
# Site name.
SITE_NAME = basename(BASE_DIR)

# Absolute filesystem path to the top-level project folder.
SITE_ROOT = dirname(BASE_DIR)

# Absolute filesystem path to the secret file which holds this project's
# SECRET_KEY. Will be auto-generated the first time this file is interpreted.


DOTENV_FILE =  join(SITE_ROOT, "deploy", ".env") 
config = Config(RepositoryEnv(DOTENV_FILE))
########## PATH CONFIGURATION
# Absolute filesystem path to this Django project directory.
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/
# Add all necessary filesystem paths to our system path so that we can use
# python import statements.
sys.path.append(SITE_ROOT)
sys.path.append(SITE_NAME)
sys.path.append(BASE_DIR)
    
########## END PATH CONFIGURATION


# SECURITY WARNING: don't run with debug turned on in production!
########## DEBUG CONFIGURATION
# Disable debugging by default.
DEBUG = False
########## END DEBUG CONFIGURATION

########## KEY CONFIGURATION
# Try to load the SECRET_KEY from our SECRET_FILE. If that fails, then generate
# a random SECRET_KEY and save it into our SECRET_FILE for future loading. If
# everything fails, then just raise an exception.


########## END KEY CONFIGURATION


BUILTIN_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'timezone_field',
    'phonenumber_field',
    'djng',
    'bootstrap3',
    
]

USER_APPS = [
    'appointmentscheduler',
    'appointmentscheduler.templatetags',
]

INSTALLED_APPS = BUILTIN_APPS + USER_APPS

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'appointmentscheduler.middleware.VisitorDetails',

]

X_FRAME_OPTIONS = 'DENY'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

ROOT_URLCONF = 'appsplatform.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join("appointmentscheduler", 'templates'),

                os.path.join("appointmentscheduler", 'templates',"Options"),
                os.path.join("appointmentscheduler", 'templates',"Options","Booking") ],

    'APP_DIRS': True,  
    'OPTIONS': {
        
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
      
    },

    
}]



WSGI_APPLICATION = 'appsplatform.wsgi.application'





# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

LOG_DIR = os.path.join( BASE_DIR, 'log')


USE_I18N = False

USE_L10N = True

USE_TZ = True

########## EMAIL CONFIGURATION

EMAIL_USE_TLS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

########## END EMAIL CONFIGURATION

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "assets")
STATICFILES_DIRS = (
os.path.join(BASE_DIR, "static"),
)
GEOIP_PATH = os.path.join(BASE_DIR,  'geopath')


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
   'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

# Application definition
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERYD_HIJACK_ROOT_LOGGER = False
CELERY_DEFAULT_QUEUE = 'normal'
CELERY_DEFAULT_EXCHANGE = 'normal'
CELERY_DEFAULT_ROUTING_KEY = 'normal'
CELERY_IGNORE_RESULT = True

CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'UTC'
CELERY_ALWAYS_EAGER = False


STATIC_URL = '/static/'


# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

import djcelery
djcelery.setup_loader()
# BROKER_URL="django:// "

########## URL CONFIGURATION
    # ROOT_URLCONF = '%s.urls' % SITE_NAME
########## END URL CONFIGURATION

