# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_supervisedregistrationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChildUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentuser', models.IntegerField()),
                ('childuser', models.IntegerField()),
            ],
        ),
    ]
