# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentscheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppschedulerInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceid', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='appointmentscheduler.AppschedulerBookings')),
            ],
            options={
                'db_table': 'appscheduler_invoices',
            },
        ),
        migrations.DeleteModel(
            name='AppschedulerBookingsServices',
        ),
    ]
