# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentscheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppschedulerCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=200, unique=True)),
                ('Alpha2', models.CharField(blank=True, max_length=6, null=True)),
                ('Alpha3', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'appscheduler_countries',
            },
        ),
        migrations.AlterUniqueTogether(
            name='appschedulercountries',
            unique_together=set([('CountryName',)]),
        ),
    ]
