# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentscheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appschedulerdates',
            name='visitor_timezone',
            field=models.CharField(default='Europe/Istanbul', max_length=32),
        ),
    ]
