# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentscheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appscheduleremployees',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appscheduleremployees',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appscheduleremployees',
            name='is_subscribed_sms',
            field=models.BooleanField(default=False),
        ),
    ]
