# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 19:46
from __future__ import unicode_literals

import appointmentscheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentscheduler', '0002_auto_20170622_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appscheduleremployees',
            name='avatar',
            field=models.ImageField(default='service/no-img.jpg', upload_to=appointmentscheduler.models.employee_img_location),
        ),
    ]
